apps:
    - id: app-a00dcd482199b927
      name: app-teste
      repo: https://github.com/nopp/app-teste.git
      branch: main
      steps:
        - name: test
          cmd: go test ./...
          sleep_sec: 0
        - name: build
          cmd: go build -o .
          sleep_sec: 10
